server:
    port: 8112
    servlet:
        context-path: /api
    # 启用 GZIP 压缩
    compression:
        enabled: true
        mime-types: application/json,application/xml,text/html,text/xml,text/plain

spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://127.0.0.1:3306/aurora?allowMultiQueries=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: bestsh-016
        druid:
            # 物理连接数
            initial-size: 5
            # 最小空闲连接数
            min-idle: 5
            # 最大活跃连接数
            max-active: 20
            # 连接等待超时时间
            max-wait: 60000
            # 配置检测连接是否有效的sql，用于测试连接是否可用，测试失败会从池中移除，默认值：SELECT 1
            validation-query: SELECT 1
            # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
            time-between-eviction-runs-millis: 60000
            # 配置一个连接在池中最小生存的时间，单位是毫秒
            min-evictable-idle-time-millis: 300000
            # 空闲时检测连接有效性
            test-while-idle: true
            # 获取连接时检测连接有效性
            test-on-borrow: false
            # 归还连接时检测连接有效性
            test-on-return: false
            # 慢SQL记录
            filter:
                stat:
                    enabled: true
                    log-slow-sql: true
                    slow-sql-millis: 2000
                wall:
                    enabled: true
            # Web 监控配置
            stat-view-servlet:
                enabled: true
                url-pattern: "/druid/*"
                login-username: admin
                login-password: admin
                allow: 127.0.0.1
                reset-enable: false
            # 配置监控信息显示在 Druid 监控页面上
            web-stat-filter:
                enabled: true
                url-pattern: "/*"
                exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/ad/*"
    data:
        redis:
            host: 127.0.0.1
            port: 6379
            database: 0